server {
    listen 80;
    server_name api.startupjigawa.com;
    location / { return 503; }
    location = /maintenance.html {
        root /usr/share/nginx/html;
        internal;
    }
    error_page 503 /maintenance.html;
}
