server {
    listen 80;
    server_name auth.startupjigawa.test;

    location / {
        set $auth_target "http://auth-service:4000";
        proxy_pass $auth_target;
    }

    location = /logo.jpeg {
        root /usr/share/nginx/html;
    }

    location = /maintenance.html {
        root /usr/share/nginx/html;
        internal;
    }
}
