server {
    listen 80;
    server_name products.startupjigawa.com;

    location / {
        proxy_pass http://products_service:3007;
    }

    location = /logo.jpeg {
        root /usr/share/nginx/html;
    }

    location = /maintenance.html {
        root /usr/share/nginx/html;
        internal;
    }
}
