server {
    listen 80;
    server_name civic.startupjigawa.com;

    location ^~ /api/ {
        proxy_pass http://api-service:4100;
    }

    location / {
        proxy_pass http://civic_service:3005;
    }

    location = /logo.jpeg {
        root /usr/share/nginx/html;
    }

    location = /maintenance.html {
        root /usr/share/nginx/html;
        internal;
    }
}
